# Generated by Django 2.2.4 on 2020-11-09 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DojoNinjaApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ninja',
            old_name='Dojo',
            new_name='dojo',
        ),
    ]
