# Generated by Django 2.2.4 on 2020-11-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DojoNinjaApp', '0002_auto_20201109_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
